# Change these first
owner: masterking32 # Your GitHub organization or username, where this repository lives
repo: masterstream_uptime # The name of this repository

sites:
  - name: Website
    check: "tcp-ping"
    url: $WEBSITE_IP
    port: 80
  - name: RESTREAM-IR-2-ParsOnline-1
    check: "tcp-ping"
    url: $IR_2
    port: $CLIENT_PORT
  - name: RESTREAM-IR-3-ParsOnline-2
    check: "tcp-ping"
    url: $IR_3
    port: $CLIENT_PORT
  - name: RESTREAM-IR-4-ParsOnline-5
    check: "tcp-ping"
    url: $IR_4
    port: $CLIENT_PORT
  - name: RESTREAM-IR-5-ZirSakht-1
    check: "tcp-ping"
    url: $IR_5
    port: $CLIENT_PORT
  - name: RESTREAM-IR-6-Afranet-1
    check: "tcp-ping"
    url: $IR_6
    port: $CLIENT_PORT
  - name: RESTREAM-IR-7-ParsOnline-3
    check: "tcp-ping"
    url: $IR_7
    port: $CLIENT_PORT
  - name: RESTREAM-IR-9-Afranet-2
    check: "tcp-ping"
    url: $IR_9
    port: $CLIENT_PORT
  - name: RESTREAM-IR-10-ParsOnline-4
    check: "tcp-ping"
    url: $IR_10
    port: $CLIENT_PORT
  - name: RESTREAM-IR-11-ZirSakht-2
    check: "tcp-ping"
    url: $IR_11
    port: $CLIENT_PORT
  - name: RESTREAM-IR-12-ZirSakht-3
    check: "tcp-ping"
    url: $IR_12
    port: $CLIENT_PORT
  - name: RESTREAM-IR-13-Afranet-3
    check: "tcp-ping"
    url: $IR_13
    port: $CLIENT_PORT
  - name: RESTREAM-IR-14-Afranet-4
    check: "tcp-ping"
    url: $IR_14
    port: $CLIENT_PORT
  - name: RESTREAM-TR-1
    check: "tcp-ping"
    url: $TR_1
    port: $CLIENT_PORT
  - name: RESTREAM-EDGE-DE-1
    check: "tcp-ping"
    url: $DE_1
    port: $CLIENT_PORT
  - name: RESTREAM-EDGE-DE-2
    check: "tcp-ping"
    url: $DE_2
    port: $CLIENT_PORT
  - name: RESTREAM-EDGE-DE-3
    check: "tcp-ping"
    url: $DE_3
    port: $CLIENT_PORT
  - name: RESTREAM-EDGE-DE-4
    check: "tcp-ping"
    url: $DE_4
    port: $CLIENT_PORT
  - name: RESTREAM-EDGE-DE-5
    check: "tcp-ping"
    url: $DE_5
    port: $CLIENT_PORT

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: stats.masterstream.ir
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.discordapp.com/attachments/733899044551655526/860481528580014080/MasterStream-Logo.png
  name: stats.masterstream.ir
  theme: dark

i18n:
  footer: <a href="https://masterstream.ir" target="_blank">MasterStream.iR</a>
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
