# Change these first
owner: masterking32 # Your GitHub organization or username, where this repository lives
repo: masterstream_uptime # The name of this repository

sites:
  - name: Website
    check: "tcp-ping"
    url: $WEBSITE_IP
    port: 80
  - name: Iran 1 - AsiaTech
    check: "tcp-ping"
    url: $IR1
    port: $CLIENT_PORT
  - name: Iran 2 - MobinNet
    check: "tcp-ping"
    url: $IR2
    port: $CLIENT_PORT
  - name: Iran 3 - Ava
    check: "tcp-ping"
    url: $IR3
    port: $CLIENT_PORT
  - name: Russia 1
    check: "tcp-ping"
    url: $RU1
    port: $CLIENT_PORT
  - name: Germany 1
    check: "tcp-ping"
    url: $DE1
    port: $CLIENT_PORT
  - name: Slovakia 1
    check: "tcp-ping"
    url: $SL1
    port: $CLIENT_PORT
  - name: Sweden 1
    check: "tcp-ping"
    url: $SE1
    port: $CLIENT_PORT
  - name: Out - Germany 1
    check: "tcp-ping"
    url: $ODE_1
    port: $CLIENT_PORT
  - name: Out - France 1
    check: "tcp-ping"
    url: $OFR_1
    port: $CLIENT_PORT
  - name: Chat Support
    check: "tcp-ping"
    url: $Chat_Support
    port: $CLIENT_PORT

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: stats.masterstream.ir
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://masterstream.ir/template/modules/main_template/images/logo-sm.png
  name: stats.masterstream.ir
  theme: dark
  navbar:
    - title: Back to the MasterStream
      href: https://masterstream.ir
  introMessage: در این صفحه، تمام سرورهای مستراستریم جهت سرویس دهی به کاربران را مشاهده میکنید. همچنین تست پینگ سرورها از آمریکا انجام میشود و میزان در دسترس بودن سرورها در اینترنت را نمایش میدهد.

i18n:
  footer: <a href="https://masterstream.ir" target="_blank">MasterStream.iR</a>
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
