# Change these first
owner: masterking32 # Your GitHub organization or username, where this repository lives
repo: masterstream_uptime # The name of this repository

sites:
  - name: Website
    check: "tcp-ping"
    url: $WEBSITE_IP
    port: 80
  - name: Iran 1 - Afranet 1
    check: "tcp-ping"
    url: $IR_1
    port: $CLIENT_PORT
  - name: Iran 2 - Afranet 5
    check: "tcp-ping"
    url: $IR_2
    port: $CLIENT_PORT
  - name: Iran 4 - Afranet 2
    check: "tcp-ping"
    url: $IR_4
    port: $CLIENT_PORT
  - name: Iran 5 - Afranet 3
    check: "tcp-ping"
    url: $IR_5
    port: $CLIENT_PORT
  - name: Iran 6 - Afranet 4
    check: "tcp-ping"
    url: $IR_6
    port: $CLIENT_PORT
  - name: Iran 7 - ParsOnline 2
    check: "tcp-ping"
    url: $IR_7
    port: $CLIENT_PORT
  - name: Turkey 1
    check: "tcp-ping"
    url: $TR_1
    port: $CLIENT_PORT
  - name: Out - Germany 1
    check: "tcp-ping"
    url: $ODE_1
    port: $CLIENT_PORT
  - name: Out - Germany 2
    check: tcp-ping"
    url: $ODE_2
    port: $CLIENT_PORT
  - name: Out - Germany 3
    check: tcp-ping"
    url: $ODE_3
    port: $CLIENT_PORT
  - name: Out - France 1
    check: "tcp-ping"
    url: $OFR_1
    port: $CLIENT_PORT

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: stats.masterstream.ir
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.discordapp.com/attachments/733899044551655526/860481528580014080/MasterStream-Logo.png
  name: stats.masterstream.ir
  theme: dark
  navbar:
    - title: Back to the MasterStream
      href: https://masterstream.ir
  introMessage: در این صفحه، تمام سرورهای مستراستریم جهت سرویس دهی به کاربران را مشاهده میکنید. همچنین تست پینگ سرورها از آمریکا انجام میشود و میزان در دسترس بودن سرورها در اینترنت را نمایش میدهد.

i18n:
  footer: <a href="https://masterstream.ir" target="_blank">MasterStream.iR</a>
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
