# Change these first
owner: masterking32 # Your GitHub organization or username, where this repository lives
repo: masterstream_uptime # The name of this repository

sites:
  - name: Website
    check: "tcp-ping"
    url: $WEBSITE_IP
    port: 80
  - name: "Server Iran 1 - Afranet 1"
    check: "tcp-ping"
    url: $IR_1
    port: $CLIENT_PORT
  - name: "Server Iran 2 - Afranet 2"
    check: "tcp-ping"
    url: $IR_2
    port: $CLIENT_PORT
  - name: "Server Iran 3 - Afranet 3"
    check: "tcp-ping"
    url: $IR_3
    port: $CLIENT_PORT
  - name: "Server Iran 4 - Afranet 4"
    check: "tcp-ping"
    url: $IR_4
    port: $CLIENT_PORT
  - name:"Server Iran 5 - Zirsakht 1"
    check: "tcp-ping"
    url: $IR_5
    port: $CLIENT_PORT
  - name: "Server Iran 6 - Zirsakht 2 (Tabriz)"
    check: "tcp-ping"
    url: $IR_6
    port: $CLIENT_PORT
  - name: "Server Iran 7 - ParsOnline 1"
    check: "tcp-ping"
    url: $IR_7
    port: $CLIENT_PORT
  - name: "Server Iran 8 - ParsOnline 2"
    check: "tcp-ping"
    url: $IR_8
    port: $CLIENT_PORT
  - name: "Server Iran 9 - ParsOnline 3"
    check: "tcp-ping"
    url: $IR_9
    port: $CLIENT_PORT
  - name: "Server Iran 10 - Zirsakht 3"
    check: "tcp-ping"
    url: $IR_10
    port: $CLIENT_PORT
  - name: "Server Iran 11 - ParsOnline 4"
    check: "tcp-ping"
    url: $IR_11
    port: $CLIENT_PORT
  - name: "Server Iran 12 - ParsOnline 5"
    check: "tcp-ping"
    url: $IR_12
    port: $CLIENT_PORT
  - name: "Server Turkey 1"
    check: "tcp-ping"
    url: $TR_1
    port: $CLIENT_PORT
  - name: "Server Russia 1"
    check: "tcp-ping"
    url: $RU_1
    port: $CLIENT_PORT
  - name: "Out - Germany 1"
    check: "tcp-ping"
    url: $ODE_1
    port: $CLIENT_PORT
  - name: "Out - Germany 2"
    check: "tcp-ping"
    url: $ODE_2
    port: $CLIENT_PORT
  - name: "Out - Germany 3"
    check: "tcp-ping"
    url: $ODE_3
    port: $CLIENT_PORT
  - name: "Out - Germany 4"
    check: "tcp-ping"
    url: $ODE_4
    port: $CLIENT_PORT
  - name: "Out - Germany 5"
    check: "tcp-ping"
    url: $ODE_5
    port: $CLIENT_PORT
  - name: "Out - Germany 6"
    check: "tcp-ping"
    url: $ODE_6
    port: $CLIENT_PORT
  - name: "Out - France 1"
    check: "tcp-ping"
    url: $OFR_1
    port: $CLIENT_PORT

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: stats.masterstream.ir
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.discordapp.com/attachments/733899044551655526/860481528580014080/MasterStream-Logo.png
  name: stats.masterstream.ir
  theme: dark
  navbar:
    - title: Back to the MasterStream
      href: https://masterstream.ir
  introMessage: در این صفحه، تمام سرورهای مستراستریم جهت سرویس دهی به کاربران را مشاهده میکنید. همچنین تست پینگ سرورها از آمریکا انجام میشود و میزان در دسترس بودن سرورها در اینترنت را نمایش میدهد.

i18n:
  footer: <a href="https://masterstream.ir" target="_blank">MasterStream.iR</a>
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
