# Change these first
owner: masterking32 # Your GitHub organization or username, where this repository lives
repo: masterstream_uptime # The name of this repository

sites:
  - name: Website
    check: "tcp-ping"
    url: $WEBSITE_IP
    port: 80
    icon: https://masterstream.ir/images/website-icon.png
  - name: Iran 1 - Ava
    check: "tcp-ping"
    url: $IR1
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/ir.svg
  - name: Iran 2 - AsiaTech
    check: "tcp-ping"
    url: $IR2
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/ir.svg
  - name: Iran 3 - Pishgaman
    check: "tcp-ping"
    url: $IR3
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/ir.svg
  - name: Iran 4 - Respina
    check: "tcp-ping"
    url: $IR4
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/ir.svg
  - name: Iran 5 - MobinNet
    check: "tcp-ping"
    url: $IR5
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/ir.svg
  - name: Russia 1
    check: "tcp-ping"
    url: $RU1
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/ru.svg
  - name: Russia 2
    check: "tcp-ping"
    url: $RU2
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/ru.svg
  - name: Germany 1
    check: "tcp-ping"
    url: $DE1
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/de.svg
  - name: Germany 2
    check: "tcp-ping"
    url: $DE2
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/de.svg
  - name: Germany 3
    check: "tcp-ping"
    url: $DE3
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/de.svg
  - name: Out - Germany 1
    check: "tcp-ping"
    url: $ODE_1
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/de.svg
  - name: Out - France 1
    check: "tcp-ping"
    url: $OFR_1
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/flags/fr.svg
  - name: Chat Support
    check: "tcp-ping"
    url: $CHAT_SUPPORT
    port: $CLIENT_PORT
    icon: https://masterstream.ir/images/chat-icon.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: stats.masterstream.ir
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://masterstream.ir/images/logo-sm.webp
  name: stats.masterstream.ir
  theme: dark
  navbar:
    - title: Back to the MasterStream
      href: https://masterstream.ir
  introMessage: در این صفحه، تمام سرورهای مستراستریم جهت سرویس دهی به کاربران را مشاهده میکنید. همچنین تست پینگ سرورها از آمریکا انجام میشود و میزان در دسترس بودن سرورها در اینترنت را نمایش میدهد.
  themeUrl: https://masterstream.ir/stats-page.css?v=1
i18n:
  footer: <a href="https://masterstream.ir" target="_blank">MasterStream.iR</a>
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
